project:
  type: default
  output-dir: _output

format:
  html:
    toc: true
    toc-depth: 3
    theme: cosmo
    code-fold: true
    code-tools: true
  pdf:
    toc: true
    toc-depth: 3
    documentclass: article
    geometry:
      - margin=1in
    fontsize: 11pt
