/-
# Constant Acts and the Consequence-Level Relation

This module specializes the alternative-level revealed-preference theory of
`RevealedPreference.lean` to the consequence space `K`, by way of the
constant-act embedding `K ↪ χ.A`, `k ↦ (fun _ => k)`. The resulting
relations `RevealedPrefK χ e k k'` and `PairwisePrefK χ e k k'` on
consequences inherit their formal properties from the alternative-level
theorems whenever the constant acts are themselves available as
alternatives (`HasConstantActs χ`) and the relevant closure clauses hold.

The philosophical content of this specialization: having extracted a
preference order on alternatives, we now ask what it says about
*consequences*. A consequence `k` is revealed at-least-as-good as `k'`
under supposition `e` precisely when the constant act always-`k` is
revealed at-least-as-good as the constant act always-`k'` under `e`.
The pairwise consequence relation reads the same comparison through the
constant-act pair menu. The module also exposes `PairwiseRepresentableK`
for pairwise rationalizability restricted to constant-act menus.
This recovers the classical setting in which preferences are ultimately
preferences over consequences.

This module realizes the framework sketched in
`prompts/PROMPT_FOR_REVEALED_PREFERENCE_INVESTIGATION.md`, but as a
specialization of the alternative-level theory developed in
`src/RevealedPreference.lean` rather than an independent construction.
-/

import RevealedPreference

namespace ConditionalChoice

universe u v

/-! ## Constant acts -/

/-- The constant act on `K` taking value `k` everywhere. -/
@[simp] def constAct {X : Type u} {K : Type v} (k : K) : X → K :=
  fun _ => k

/-- A `ConditionalJudgment` *has constant acts* if every consequence is
    realized as a constant alternative. -/
def HasConstantActs {X : Type u} {K : Type v}
    (χ : ConditionalJudgment X K) : Prop :=
  ∀ k : K, (constAct k : X → K) ∈ χ.A

/-- The menu of constant acts generated by a set of consequences. -/
def constActMenu {X : Type u} {K : Type v} (s : Set K) : Set (X → K) :=
  (constAct : K → X → K) '' s

/-- Two constant acts are equal iff their values are equal (assuming `X` is
    inhabited, which is provided by the `ConditionalJudgment` structure). -/
theorem constAct_injective {X : Type u} {K : Type v}
    [Nonempty X] : Function.Injective (constAct : K → X → K) := by
  intro k k' h
  exact congrArg (fun f => f (Classical.arbitrary X)) h

/-! ## The revealed-preference relation on consequences -/

/-- The revealed-preference relation on `K`, defined as the pullback of
    `RevealedPref` along the constant-act embedding. -/
def RevealedPrefK {X : Type u} {K : Type v} (χ : ConditionalJudgment X K)
    (e : Set X) (k k' : K) : Prop :=
  RevealedPref χ e (constAct k) (constAct k')

/-- Strict revealed preference on consequences. -/
def StrictPrefK {X : Type u} {K : Type v} (χ : ConditionalJudgment X K)
    (e : Set X) (k k' : K) : Prop :=
  RevealedPrefK χ e k k' ∧ ¬ RevealedPrefK χ e k' k

/-- Revealed indifference on consequences. -/
def IndiffK {X : Type u} {K : Type v} (χ : ConditionalJudgment X K)
    (e : Set X) (k k' : K) : Prop :=
  RevealedPrefK χ e k k' ∧ RevealedPrefK χ e k' k

/-- The pairwise revealed-preference relation on consequences, defined as
    the pullback of `PairwisePref` along the constant-act embedding. -/
def PairwisePrefK {X : Type u} {K : Type v} (χ : ConditionalJudgment X K)
    (e : Set X) (k k' : K) : Prop :=
  PairwisePref χ e (constAct k) (constAct k')

/-- Strict pairwise revealed preference on consequences. -/
def StrictPairwisePrefK {X : Type u} {K : Type v} (χ : ConditionalJudgment X K)
    (e : Set X) (k k' : K) : Prop :=
  PairwisePrefK χ e k k' ∧ ¬ PairwisePrefK χ e k' k

/-- Pairwise revealed indifference on consequences. -/
def PairwiseIndiffK {X : Type u} {K : Type v} (χ : ConditionalJudgment X K)
    (e : Set X) (k k' : K) : Prop :=
  PairwisePrefK χ e k k' ∧ PairwisePrefK χ e k' k

/-- The set of `R'^K_e`-maximal consequences in a consequence menu. -/
def pairwiseMaxSetK {X : Type u} {K : Type v} (χ : ConditionalJudgment X K)
    (e : Set X) (s : Set K) : Set K :=
  { k | k ∈ s ∧ ∀ k' ∈ s, PairwisePrefK χ e k k' }

/-- Pairwise representability on constant-act menus, pulled back to the
    consequence space. -/
def PairwiseRepresentableK {X : Type u} {K : Type v}
    (χ : ConditionalJudgment X K) (e : Set X) : Prop :=
  ∀ s : Set K, constActMenu s ∈ χ.M →
    { k | (constAct k : X → K) ∈ χ.C e (constActMenu s) } =
      pairwiseMaxSetK χ e s

/-! ## Inherited structural properties

Each property of `RevealedPref` transports to `RevealedPrefK` whenever
constant acts are present. The proofs are immediate applications of the
alternative-level theorems. -/

/-- `R_e^K` is reflexive on `K` (uses singleton closure of constant-act
    menus and `HasConstantActs`). -/
theorem revealedPrefK_refl_at {X : Type u} {K : Type v}
    {χ : ConditionalJudgment X K}
    (hM : MenuClosure χ) (hC : HasConstantActs χ)
    {e : Set X} (he : e ∈ χ.E) :
    ∀ k : K, RevealedPrefK χ e k k :=
  fun k => revealedPref_refl_at hM he (constAct k) (hC k)

/-- `R_e^K` is total on `K` (uses pair closure of constant-act menus and
    `HasConstantActs`). -/
theorem revealedPrefK_total_at {X : Type u} {K : Type v}
    {χ : ConditionalJudgment X K}
    (hM : MenuClosure χ) (hC : HasConstantActs χ)
    {e : Set X} (he : e ∈ χ.E) :
    ∀ k k' : K,
      RevealedPrefK χ e k k' ∨ RevealedPrefK χ e k' k :=
  fun k k' =>
    revealedPref_total_at hM he (constAct k) (constAct k') (hC k) (hC k')

/-- `R_e^K` is transitive on `K` under WARP and triple closure. -/
theorem revealedPrefK_trans_via_warp {X : Type u} {K : Type v}
    {χ : ConditionalJudgment X K}
    (hM : MenuClosure χ) (hC : HasConstantActs χ)
    {e : Set X} (he : e ∈ χ.E) (hWARP : WARPAt χ e) :
    ∀ k₁ k₂ k₃ : K,
      RevealedPrefK χ e k₁ k₂ →
      RevealedPrefK χ e k₂ k₃ →
      RevealedPrefK χ e k₁ k₃ :=
  fun k₁ k₂ k₃ =>
    revealedPref_trans_via_warp hM he hWARP
      (constAct k₁) (constAct k₂) (constAct k₃)
      (hC k₁) (hC k₂) (hC k₃)

/-- `R_e^K` is a weak ordering on `K`: reflexive, transitive, total. -/
def WeakOrderingKAt {X : Type u} {K : Type v}
    (χ : ConditionalJudgment X K) (e : Set X) : Prop :=
  (∀ k : K, RevealedPrefK χ e k k) ∧
  (∀ k₁ k₂ k₃ : K,
      RevealedPrefK χ e k₁ k₂ →
      RevealedPrefK χ e k₂ k₃ →
      RevealedPrefK χ e k₁ k₃) ∧
  (∀ k k' : K,
      RevealedPrefK χ e k k' ∨ RevealedPrefK χ e k' k)

/-- Under `MenuClosure`, `HasConstantActs`, and WARP, `R_e^K` is a weak
    ordering on `K`. -/
theorem revealedPrefK_weakOrder_at {X : Type u} {K : Type v}
    {χ : ConditionalJudgment X K}
    (hM : MenuClosure χ) (hC : HasConstantActs χ)
    {e : Set X} (he : e ∈ χ.E) (hWARP : WARPAt χ e) :
    WeakOrderingKAt χ e :=
  ⟨ revealedPrefK_refl_at hM hC he,
    revealedPrefK_trans_via_warp hM hC he hWARP,
    revealedPrefK_total_at hM hC he ⟩

/-- Pairwise revealed preference on consequences implies ordinary revealed
    preference on consequences whenever constant acts are alternatives. -/
theorem pairwisePrefK_imp_revealedPrefK {X : Type u} {K : Type v}
    {χ : ConditionalJudgment X K}
    (hM : MenuClosure χ) (hC : HasConstantActs χ)
    {e : Set X} {k k' : K} :
    PairwisePrefK χ e k k' → RevealedPrefK χ e k k' :=
  pairwisePref_imp_revealedPref hM (hC k) (hC k')

/-- Under WARP, consequence-level revealed preference is witnessed by the
    constant-act pair menu. -/
theorem revealedPrefK_imp_pairwisePrefK_of_warp {X : Type u} {K : Type v}
    {χ : ConditionalJudgment X K}
    (hM : MenuClosure χ) (hC : HasConstantActs χ)
    {e : Set X} (he : e ∈ χ.E) (hWARP : WARPAt χ e)
    {k k' : K} :
    RevealedPrefK χ e k k' → PairwisePrefK χ e k k' :=
  revealedPref_imp_pairwisePref_of_warp hM he hWARP (hC k) (hC k')

/-- Alternative-level pairwise representability restricts to pairwise
    representability on constant-act consequence menus. -/
theorem pairwiseRepresentableK_of_pairwiseRepresentable {X : Type u} {K : Type v}
    {χ : ConditionalJudgment X K} {e : Set X}
    (hPairRep : PairwiseRepresentable χ e) : PairwiseRepresentableK χ e := by
  intro s hs
  haveI : Nonempty X := χ.X_nonempty
  ext k
  constructor
  · intro hk
    have hmax : (constAct k : X → K) ∈ pairwiseMaxSet χ e (constActMenu s) := by
      rw [← hPairRep (constActMenu s) hs]
      exact hk
    obtain ⟨hk_mem, hk_max⟩ := hmax
    obtain ⟨k₀, hk₀s, hk₀eq⟩ := hk_mem
    have hk₀_eq : k₀ = k := constAct_injective hk₀eq
    refine ⟨?_, ?_⟩
    · rwa [hk₀_eq] at hk₀s
    · intro k' hk's
      exact hk_max (constAct k') ⟨k', hk's, rfl⟩
  · intro hk
    rw [hPairRep (constActMenu s) hs]
    obtain ⟨hks, hk_max⟩ := hk
    refine ⟨⟨k, hks, rfl⟩, ?_⟩
    rintro _ ⟨k', hk's, rfl⟩
    exact hk_max k' hk's

/-! ## Event independence on consequences

Event-independence has cleaner philosophical content at the consequence
level than at the alternative level: it asks whether the agent's
*intrinsic* preferences over consequences shift with the supposition,
distinguishing genuinely state-dependent from state-independent valuation. -/

/-- Event-independence of the consequence-level relation: `R_e^K` and
    `R_{e'}^K` agree on all consequences for all events `e, e' ∈ χ.E`. -/
def EventIndependentRK {X : Type u} {K : Type v}
    (χ : ConditionalJudgment X K) : Prop :=
  ∀ e e', e ∈ χ.E → e' ∈ χ.E →
    ∀ k k' : K,
      (RevealedPrefK χ e k k' ↔ RevealedPrefK χ e' k k')

/-- If the underlying alternative-level relation is event-independent and
    constant acts are present, then so is the consequence-level relation. -/
theorem eventIndependentRK_of_eventIndependentR {X : Type u} {K : Type v}
    {χ : ConditionalJudgment X K} (hC : HasConstantActs χ)
    (hEI : EventIndependentR χ) : EventIndependentRK χ := by
  intro e e' he he' k k'
  exact hEI e e' he he' (constAct k) (constAct k') (hC k) (hC k')

end ConditionalChoice
